title                    : "Glenn Sarti (DEV)"
url                      : ""
port                     : 4000

sass:
  style:            :expanded

# Analytics
analytics:
  provider               : false  # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          :

# Minimal Mistakes Theme information
# The gem theme is only need when in Dev mode, otherwise github complains.
theme: minimal-mistakes-jekyll
